[versions]
gradle-versions = "0.52.0" # https://github.com/ben-manes/gradle-versions-plugin/releases
kotlin = "2.1.21" # https://kotlinlang.org/docs/releases.html#release-details

kotlinx-coroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md
kotlinx-serialization-json = "1.8.1"

[libraries]
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[plugins]
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
